# if none are set, everything is included
# include: ONLY use this project for these versions
# exclude: use this project for all versions EXCEPT for these
# include and exclude can't be used at the same time
#
# force-versions: force download this modrinth url version for speicific mc version (see example for sodium)
#
# EXAMPLE:
# {
#     "mods":               [{"id": "yosbr",
#                                 "include": ["x.x.x", "x.x.x"]},
#                             {"id": "moreculling",
#                                 "exclude": ["x.x.x", "x.x.x"]},
#                             {"id": "sodium",
#                                 "force-versions": {
#                                     "1.21.4": "https://modrinth.com/mod/sodium/version/mc1.21.4-0.6.10-fabric", # use url!
#                                     "1.21.1": "https://modrinth.com/mod/sodium/version/mc1.21.1-0.6.9-fabric"
#                                 }}
#                            ]
# }

{
    "mods": [
        {"id": "yosbr",
            "force-versions": {
                "1.21.5": "KMOzdYko"
        }},
        {"id": "moreculling"},
        {"id": "modmenu"},
        {"id": "iris"},
        {"id": "dynamic-fps"},
        {"id": "sodium",
            "force-versions": {
                "1.21.3": "LL4puCl1" # 0.6.8+1.21.3 instead of 0.6.9+1.21.3
        }},
        {"id": "morechathistory"},
        {"id": "capes"},
        {"id": "zoomify"},
        {"id": "ferrite-core"},
        {"id": "sodium-extra"},
        {"id": "immediatelyfast"},
        {"id": "language-reload"},
        {"id": "lambdynamiclights"},
        {"id": "badoptimizations"},
        {"id": "entity-model-features"},
        {"id": "entitytexturefeatures"},
        {"id": "lighty"},
        {"id": "better-stats"},
        {"id": "music-notification"},
        {"id": "status-effect-bars"},
        {"id": "mace-but-3d",
            "include": ["1.21.1", "1.21.3"]},
        {"id": "glowing-torchflower"},
        {"id": "detail-armor-bar"},
        {"id": "visuality"},
        {"id": "simple-voice-chat",
            "force-versions": {
                "1.21.3": "Uov7kAax" # 1.21.3-2.5.26 instead of 1.21.3-2.5.28
        }},
        {"id": "chat-heads"},
        {"id": "mouse-tweaks"},
        {"id": "clientsort"},
        {"id": "bobby"},
        {"id": "fastquit"},
        {"id": "mixintrace"},
        {"id": "e4mc"},
        {"id": "modelfix"},
        {"id": "entityculling"},
        {"id": "fabrishot"},
        {"id": "controlify"},
        {"id": "lithium"},
        {"id": "appleskin"},
        {"id": "modernfix"},
        {"id": "cubes-without-borders"},
        {"id": "better-mount-hud"},
        {"id": "ebe"},
        {"id": "continuity"},
        {"id": "nuit"},          # For some reason the ids fabricskyboxes and fabricskyboxes-interop have changed to nuit and nuit-interop
        {"id": "nuit-interop"},
        {"id": "noisium"},
        {"id": "litematica"},
        {"id": "shulkerboxtooltip"},
        {"id": "betterf3"},
        {"id": "eating-animation",
            "include": ["1.20.1", "1.20.4", "1.21.1", "1.21.3"]},
        {"id": "pick-up-notifier"},
        {"id": "cherished-worlds"},
        {"id": "polytone"},
        {"id": "world-play-time"},
        {"id": "skinshuffle",
            "force-versions": {
                "1.21.4": "QrivRDWz" # to avoid launch crash, see https://github.com/IMB11/SkinShuffle/issues/145
        }},
        {"id": "no-resource-pack-warnings"},
        {"id": "infinite-music"},
        {"id": "particular"},
        {"id": "3dskinlayers"},
        {"id": "auth-me"},
        {"id": "inventory-blur"},
        {"id": "calcmod"},
        {"id": "chunky"},
        {"id": "better-f1-reborn"},
        {"id": "xaeros-world-map"},
        {"id": "xaeros-minimap"},
        {"id": "xaeroplus"},
        {"id": "not-enough-animations"},
        {"id": "fast-ip-ping"},
        {"id": "extended-world-selection",
            "force-versions": {
                "1.21.4": "ctbaxlx5" # use 1.21.3 version for 1.21.4, works just fine
            }},
        {"id": "clumps"},
        {"id": "legendary-tooltips"},
        {"id": "flashback"},
        {"id": "bettercommandblockui"},
        {"id": "improved-sign-editing"},
        {"id": "bindcommands"},
        {"id": "fallingleaves"},
        {"id": "no-chat-reports"},
        {"id": "better-advancements"},
        {"id": "indium"},
        {"id": "resourcify"},
        {"id": "craftpresence"},
        {"id": "advancement-plaques"},
        {"id": "krypton"},
        {"id": "make_bubbles_pop"},
        {"id": "screenshot-viewer"},
        {"id": "seamless-loading-screen"},
        {"id": "screenshot-to-clipboard"},
        {"id": "chunks-fade-in"},
        {"id": "optigui"},
        {"id": "animatica"},
        {"id": "custom-credits"},
        {"id": "dynamiccrosshair"},
        {"id": "show-me-your-skin"},
        {"id": "controlling"},
        {"id": "durability-plus"},
        {"id": "hey-wiki",
            "force-versions": {
                "1.21.3": "7r51NSUr" # 1.7.2+1.21.3 instead of 1.7.3+1.21.4
        }},
        {"id": "sound-controller"},
        {"id": "debugify"},
        {"id": "my-resource-pack"},
        {"id": "gamma-utils"},
        {"id": "sound",
            "exclude": ["1.21.5"]}, # causes a crash on startup. remove line when fixed
        {"id": "xanders-sodium-options"},
        {"id": "explosive-enhancement"},
        {"id": "cat_jam"},
        {"id": "cave-dust"},
        {"id": "fast-trading"},
        {"id": "creative-fly"},
        {"id": "options-profiles"},
        {"id": "emotecraft"},
        {"id": "online-emotes"},
        {"id": "armor-trim-item-fix",
            "include": ["1.20.1", "1.20.4", "1.21.1", "1.21.3", "1.21.4"]},
        {"id": "jade"},
        {"id": "rei"},
        {"id": "entity-view-distance"},
        {"id": "simplefog"},
        {"id": "swd-panorama"},
        {"id": "better-suggestions"},
        {"id": "waxedicons"},
        {"id": "subtle-effects"},
        {"id": "item-highlighter"},
        {"id": "scribble"},
        {"id": "symbol-chat"},
        {"id": "autorun"},
        {"id": "skin-grabber"},
        {"id": "voicechat-soundboard"},
        {"id": "wider-tab"},
        {"id": "viewboboptions"},
        {"id": "fancymenu"},
        {"id": "rsls"},
        {"id": "chatanimation"},
        {"id": "withered-hearts"},
        {"id": "mod-loading-screen"},
        {"id": "vtdownloader"},
        {"id": "respackopts"},
        {"id": "mod-sets",
            "force-versions": {
                "1.21.4": "dYzIIsk2" # use 1.21.1 version
        }},
        {"id": "kinecraft-serialization",
            "force-versions": {
                "1.21.4": "ppUfV7UC" # use 1.21 version
        }},
        {"id": "worldedit"}],
#        {"id": "better-clouds"},
#        {"id": "distanthorizons"}],
    "shaderpacks": [
        {"id": "makeup-ultra-fast-shaders"},
        {"id": "miniature-shader"},
        {"id": "solas-shader"},
        {"id": "rethinking-voxels"},
        {"id": "complementary-unbound"},
        {"id": "bsl-shaders"},
        {"id": "complementary-reimagined"},
        {"id": "bliss-shader"},
        {"id": "super-duper-vanilla"}],
    "resourcepacks": [
        {"id": "default-splashes"},
        {"id": "fullbright-ub"},
        {"id": "fresh-animations"},
        {"id": "visuals",
            "exclude": ["1.20.1", "1.20.4", "1.21.1", "1.21.3", "1.21.4"]},
        {"id": "icons",
            "force-versions": {
                "1.21.3": "iM6mxyAW",
                "1.21.4": "iM6mxyAW",
                "1.21.5": "iM6mxyAW"
            }},
        {"id": "better-flame-particles"},
        {"id": "simple-grass-flowers"},
        {"id": "mob-crates"},
        {"id": "fancy-crops"},
        {"id": "qraftys-capitalized-font"},
        {"id": "enchant-icons-countxd"},
        {"id": "even-better-enchants"},
        {"id": "cubic-sun-moon"},
        {"id": "redstone-tweaks",
            "force-versions": {
                "1.21.5": "G3HClwKQ"
            }},
        {"id": "low-on-fire"},
        {"id": "tras-fresh-player"},
        {"id": "better-leaves"},
        {"id": "3d-plants"},
        {"id": "spectral"},
        {"id": "reimagined"},
        {"id": "hyper-realistic-sky"},
        {"id": "grimdark-sky"},
        {"id": "animated-items"},
        {"id": "better-lanterns"},
        {"id": "dramatic-skys"},
        {"id": "new-glowing-ores"},
        {"id": "bow-load-indicator"},
        {"id": "chat-reporting-helper"},
        {"id": "spryzeens-knight-armor"},
        {"id": "spryzeens-healthbars"},
        {"id": "colourful-containers-gui",
            "force-versions": {
                "1.21.5": "AnsTNrER"
        }},
        {"id": "colourful-containers-dark-mode-gui",
            "force-versions": {
                "1.21.5": "aSv3SdMO"
        }},
        {"id": "translations-for-sodium"},
        {"id": "spawned-eggs",
            "include": ["1.20.1", "1.20.4", "1.21.1", "1.21.3", "1.21.4"]},
        {"id": "icons-advertisement-removal"},
        {"id": "theones-eating-animation-pack",
            "exclude": ["1.20.1", "1.20.4", "1.21.1", "1.21.3"]},
        {"id": "default-dark-mode",
            "force-versions": {
                "1.21.3": "KW0bu9nm",
                "1.21.4": "KW0bu9nm",
                "1.21.5": "KW0bu9nm"
            }},
        {"id": "bare-bones"},
        {"id": "meme-soundboard"},
        {"id": "thfa"},
        {"id": "torturable-healthbars"},
        {"id": "mace-but-3d-resourcepack",
            "exclude": ["1.20.1", "1.20.4", "1.21.1", "1.21.3"]}
    ]
}
